### ISSUE TITLE
Convenience: Add unix shebang. Make --info argument optional as it's the only argument anyhow.

### ISSUE THREAD

**Issue by porg** [ross-spencer/zbthumbnail-extractor#1]
# Goal
- You can conveniently run this script with minimal synthax

# For more convenience
- Offer the python file with a [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) at the first line:
`#!/usr/bin/env python`
- Then in order to run on Unix systems you do not need to prefix the script with `python `
  - Just drop it into your script/executable folder i.e. `~/bin/` which is in your environment path
  - `chmod +x ~/bin/zbextractor.py`to make it executable
  - From then on you can just call it with `zbextractor.py`
  - A bit inconvenient is that you need the explicit `--info` argument, though the script anyhow only takes one argument. A bit verbose.

**Comment by ross-spencer** [comment]
Thanks @porg this is a useful reminder to do some maintenance on this one. Added the shebang here: https://github.com/ross-spencer/zbthumbnail-extractor/commit/33d194658f42a090468a0afb948e25a4faa64abe - point taken too about `--info` will have a think but won't change it just now. Added a note to a new issue about that.
