### ISSUE TITLE
Thumbnail directory and files in it only works on Windows

### ISSUE THREAD

**Issue by porg** [ross-spencer/zbthumbnail-extractor#2]
# Foreword
With #1 I already adapted the script better to Unix.

# Problem
If you run this as-is on a Unix system like i.e. macOS 11 Big Sur the thumbnail directory and files which it attempts to create create an undesired result.

In the folder holding the Thumbs.db or ZbThumbnail.info file
- the script created a folder `Thumbs-<longUID>` which is ok as intended
and as siblings:
- `Thumbs-<longUID>\image-0001.jpg` as a file with the backslash in the filename.
- `Thumbs-<longUID>\image-0001.jpg` also as a file
- … and so on

# Reason
**Line 69**: Shows that it uses backslash as a hardcoded path separator
```python
jpg = open(dirname + '\image-' + str(tncount).zfill(4) + '.jpg', 'wb')
```

# Fix for Unix
If you change `\image-` to `/image-` then this works also on Unix.

# Goal
Change the code so that it automatically uses the correct path separator for the platform the script runs on.
I have no idea how to do that correctly in Python, but it's easy for Python-savvy scripters/developers for sure.

**Comment by ross-spencer** [comment]
Thanks @porg good suggestion - have a look at the solution in https://github.com/ross-spencer/zbthumbnail-extractor/commit/eade8a749045666022dc4e2b1790ba97150751bc and see what you think. This approach should make it platform independent and avoid the string manipulation I was doing here in the past. May be useful for your future reviews. Thanks for the engagement here, it's really appreciated.
